version: "3.9"

services:
  flask_app:
    container_name: flyr
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always
